name: Testes

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v1

            - name: instalação do jest
              run: npm install jest

            - name: execução dos testes
              run: npm test
